#!/usr/bin/env bash
set -e

# Check if vagrant is installed.
if ! [ -x "$(command -v vagrant)" ]; then
  echo 'Error: vagrant is not installed.' >&2
  exit 1
fi

# Check if the test run before.
if [ -e "andock-vagrant-test" ]; then
    echo "Folder andock-vagrant-test already exists. Run vagrant destroy and rm -r andock-vagrant-test"
    exit 1
fi
# Ask for ssh key
read -e -p "Which SSH key should be used?: [~/.ssh/id_rsa.pub]" KEY

if [ "$KEY" == "" ]; then
    KEY="~/.ssh/id_rsa.pub"
fi

eval KEY=$KEY
if [ ! -e "$KEY" ]; then
    echo "SSH key not found"
    exit 1
fi

mkdir andock-vagrant-test
cd andock-vagrant-test

# Download vagrant file.
curl --output Vagrantfile https://raw.githubusercontent.com/andock/andock/master/tests/vagrant/Vagrantfile

sed -i -e "s,id_rsa.pub,$KEY,g" "Vagrantfile"

# Start vagrant
vagrant up
echo ""
echo "##########################################################################"
echo "Vagrant is up"
echo
echo "Please copy following lines to your /etc/hosts"
echo "192.168.33.10    andock.vagrant"
echo "192.168.33.10    master.demo-project.andock.vagrant"
echo "192.168.33.10    develop.demo-project.andock.vagrant"
echo
echo ""
echo "You should now connect to the vagrant box with ssh root@andock.vagrant"
echo ""
echo "Go to now demo-project and follow the 5 minutes guide"
echo
echo "##########################################################################"
echo ""

